### ISSUE TITLE
Removing the ` if it's used to open the console

### ISSUE THREAD

**Issue by thebspin** [pointcache/Unity3d-BeastConsole#3]
Whenever the backquote is being used to open the console it's also the first character that is being shown after typing a letter. Maybe it could be made that when the backquote is the opening key it should be stripped from the input whenever the console is just being opened.

![image](https://cloud.githubusercontent.com/assets/203133/18740801/e8652f82-80ab-11e6-9915-87e391967806.png)

**Comment by pointcache** [comment]
it strips it already, should be a bug

**Comment by the-mr-matt** [comment]
This issue is happening for me. Was it ever fixed?
